DROP TABLE TB_CUSTOMER PURGE;

CREATE TABLE TB_CUSTOMER(
	ID VARCHAR2(100) PRIMARY KEY,
	PASSWORD VARCHAR2(200) NOT NULL,
	NAME VARCHAR2(100) NOT NULL
);

INSERT INTO TB_CUSTOMER VALUES('admin', 'admin1234', '관리자');
INSERT INTO TB_CUSTOMER VALUES('dd', 'dd1234', '디디');
SELECT * FROM TB_CUSTOMER;