-- FAM SEQUENCE SQL
DROP SEQUENCE FAMNO_SEQ;
CREATE SEQUENCE FAMNO_SEQ;

-- FAM Table SQL
DROP TABLE FAM;
CREATE TABLE FAM
(
    MEMBERNO       NUMBER           NOT NULL, 
    FAMNO          NUMBER           NOT NULL, 
    FAMNAME        VARCHAR2(100)    NOT NULL, 
    FAMHEIGHT      NUMBER           NOT NULL, 
    FAMDISEASE1    VARCHAR2(50)     NULL, 
    FAMDISEASE2    VARCHAR2(50)     NULL, 
    FAMDISEASE3    VARCHAR2(50)     NULL, 
    FAMBIRTH       VARCHAR2(50)     NOT NULL, 
    FAMLUNAR       VARCHAR2(20)     NOT NULL, 
    CONSTRAINT FAM_PK PRIMARY KEY (FAMNO),
    CONSTRAINT FAM_FK FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
    CONSTRAINT FAM_LUNAR_CHK CHECK(FAMLUNAR IN ('Y','N'))
);

INSERT INTO FAM VALUES(1, FAMNO_SEQ.NEXTVAL, '엄마', '160', '당뇨', '지방간', '빈혈', '19620220', 'N');

SELECT * FROM FAM;