-- FAM SEQUENCE SQL
DROP SEQUENCE FAMNO_SEQ;
CREATE SEQUENCE FAMNO_SEQ;

-- FAM Table SQL
DROP TABLE FAM;
CREATE TABLE FAM
(
    MEMBERNO       NUMBER           NOT NULL, 
    FAMNO          NUMBER           NOT NULL, 
    FAMNAME        VARCHAR2(100)    NOT NULL, 
    FAMHEIGHT      NUMBER           NOT NULL, 
    FAMDISEASE1    VARCHAR2(50)     NULL, 
    FAMDISEASE2    VARCHAR2(50)     NULL, 
    FAMDISEASE3    VARCHAR2(50)     NULL, 
    FAMBIRTH       NUMBER           NOT NULL, 
    FAMLUNAR       VARCHAR2(20)     NOT NULL, 
    CONSTRAINT FAM_PK PRIMARY KEY (FAMNO),
    CONSTRAINT FAM_FK FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
    CONSTRAINT FAM_LUNAR_CHK CHECK(FAMLUNAR IN ('양력','음력'))
);

INSERT INTO FAM VALUES(1, FAMNO_SEQ.NEXTVAL, '엄마', '160', '당뇨병', '지방간', '빈혈', '19620220', 'N');
ALTER TABLE FAM MODIFY(FAMBIRTH NUMBER);
UPDATE FAM SET FAMDISEASE1 = '당뇨병' WHERE FAMNO = 1;

SELECT * FROM FAM;

---------------------------------------------------------------------------

--HEATL TABLE SQL
DROP TABLE HEAlTH;
CREATE TABLE HEALTH
(
    FAMNO           NUMBER     REFERENCES  FAM(FAMNO) ON DELETE CASCADE,
    HEALTHWEIGHT    NUMBER     NOT NULL, 
    HEALTHSHRBP     NUMBER     NOT NULL, 
    HEALTHRELBP     NUMBER     NOT NULL, 
    HEALTHDATE      DATE   	   NOT NULL
);

INSERT INTO HEALTH VALUES(1, 80, 100, 80, SYSDATE);

SELECT * FROM HEALTH;

SELECT * FROM HEALTH WHERE FAMNO=1;

--1. famno에 해당하는 열만 검색
SELECT * FROM HEALTH WHERE FAMNO=1;
--2. 최신 순으로 정렬 후 다섯개만 검색
SELECT * FROM(
SELECT A.FAMNO, A.HEALTHWEIGHT, A.HEALTHSHRBP,  A.HEALTHRELBP, A.HEALTHDATE, ROWNUM 
FROM(SELECT * FROM HEALTH WHERE FAMNO=1 ORDER BY HEALTHDATE DESC) A ) B
WHERE B.FAMNO=1 

AND ROWNUM >= 5; AND ROWNUM >= 1;


SELECT * FROM 
	(SELECT A.ENAME, A.SAL, ROWNUM AS R 
	FROM (SELECT ENAME,SAL FROM EMP ORDER BY SAL DESC) A) B 
WHERE B.R >2 AND B.R <= 5;
SELECT * FROM (
SELECT FAMNO, HEALTHWEIGHT, HEALTHSHRBP, HEALTHRELBP, HEALTHDATE, ROWNUM 
FROM( SELECT * FROM HEALTH WHERE FAMNO=1)
ORDER BY HEALTHDATE DESC)
WHERE ROWNUM <= 5

SELECT * FROM (
SELECT *
FROM( SELECT * FROM HEALTH WHERE FAMNO=1)
ORDER BY HEALTHDATE DESC)
WHERE ROWNUM <= 5
ORDER BY HEALTHDATE


----------------------------------------------------

--MENU TABLE SQL
DROP TABLE MENU;
CREATE TABLE MENU
(
    MENUDISEASE    VARCHAR2(100)    NOT NULL, 
    MENUIMG        VARCHAR2(100)    NOT NULL, 
    CONSTRAINT MENU_PK PRIMARY KEY (MENUDISEASE)
);

INSERT INTO MENU VALUES('당뇨병','당뇨병 식단');
INSERT INTO MENU VALUES('심근경색증','심근경색증 식단');
INSERT INTO MENU VALUES('심부전증','심부전증 식단');
INSERT INTO MENU VALUES('지방간','지방간 식단');
INSERT INTO MENU VALUES('빈혈','빈혈 식단');
INSERT INTO MENU VALUES('알츠하이머','알츠하이머 식단');
INSERT INTO MENU VALUES('골다골증','골다골증 식단');
INSERT INTO MENU VALUES('간암','간암 식단');
INSERT INTO MENU VALUES('갑상선암','갑상선암 식단');
INSERT INTO MENU VALUES('대장암','대장암 식단');
INSERT INTO MENU VALUES('위암','위암 식단');
INSERT INTO MENU VALUES('유방암','유방암 식단');
INSERT INTO MENU VALUES('전립선암','전립선암 식단');


