--FWL SEQUENCE SQL
DROP SEQUENCE FWLNO_SEQ;
CREATE SEQUENCE FWLNO_SEQ;

--FWL TABLE SQL
DROP TABLE FWL;
CREATE TABLE FWL
(
    MEMBERNO    NUMBER           NOT NULL, 
    FWLNO       NUMBER           NOT NULL, 
    FWLITEM     VARCHAR2(200)    NOT NULL, 
    FWLCHK      VARCHAR2(20)     NOT NULL, 
    CONSTRAINT FWL_PK PRIMARY KEY (FWLNO),
    CONSTRAINT FWL_FK FOREIGN KEY (MEMBERNO) REFERENCES MEMBER (MEMBERNO),
    CONSTRAINT FWL_CHK CHECK(FWLCHK IN ('Y','N'))
);

SELECT * FROM FWL;
INSERT INTO FWL VALUES(41, FWLNO_SEQ.NEXTVAL, '맛있는거 먹으러 가기', 'N');

