--GG SEQUENCE SQL
DROP SEQUENCE GGNO_SEQ;
CREATE SEQUENCE GGNO_SEQ;

--GG TABLE SQL
DROP TABLE GG;
CREATE TABLE GG
(
    GGNO         NUMBER            NOT NULL,
    GGROWNUM     NUMBER			   NULL,
    GGWRITER     VARCHAR2(100)     NOT NULL, 
    GGTITLE      VARCHAR2(200)     NOT NULL, 
    GGCONT       VARCHAR2(4000)    NOT NULL, 
    GGREADCNT    NUMBER            NOT NULL, 
    GGDATE       DATE              NOT NULL, 
    CONSTRAINT GG_PK PRIMARY KEY (GGNO)
);

INSERT INTO GG VALUES(GGNO_SEQ.NEXTVAL, null, '관리자', '좋은 글 게시판 1', '테스트 페이지에용', 0, SYSDATE);

SELECT * FROM GG;

SELECT * FROM(
SELECT * FROM GG ORDER BY GGDATE DESC)
WHERE ROWNUM=1;
	 
------------------------------------------------

--GGCM SEQUENCE SQL
DROP SEQUENCE GGCMNO_SEQ;
CREATE SEQUENCE GGCMNO_SEQ;

--GGCM TABLE SQL
DROP TABLE GGCM;
CREATE TABLE GGCM
(
    GGNO          NUMBER            REFERENCES  GG(GGNO) ON DELETE CASCADE,
    GGCMNO        NUMBER            NOT NULL, 
    GGCMWRITER    VARCHAR2(100)     NOT NULL, 
    GGCMCONT      VARCHAR2(1000)    NOT NULL, 
    GGCMDATE      DATE              NOT NULL, 
    CONSTRAINT GGCM_PK PRIMARY KEY (GGCMNO)
);

INSERT INTO GGCM VALUES(1, GGCMNO_SEQ.NEXTVAL, '관리자', '기운냈으면 좋겟댱 ', SYSDATE);

SELECT * FROM GGCM;



------------------------------------------------

--GGIMG SEQUENCE SQL
DROP SEQUENCE GGIMGNO_SEQ;
CREATE SEQUENCE GGIMGNO_SEQ;

--GGIMG TABLE SQL
DROP TABLE GGIMG;
CREATE TABLE GGIMG
(
    GGIMGNO      	   NUMBER           NOT NULL, 
    GGNO               NUMBER           REFERENCES  GG(GGNO) ON DELETE CASCADE, 
    GGIMGORIGINALNAME  VARCHAR2(260)    NOT NULL,
    GGIMGSTORENAME     VARCHAR2(50)     NOT NULL,
    GGIMGSIZE          NUMBER 			NULL,
    GGIMGDATE          DATE             NOT NULL, 
    GGIMGCREATUSER     VARCHAR2(30)     NOT NULL,
    GGIMGDEL  		   VARCHAR2(4)      NOT NULL,
    CONSTRAINT GGIMG_PK PRIMARY KEY (GGIMGNO),
    CONSTRAINT GGIMG_DEL CHECK(GGIMGDEL IN ('Y','N'))
);

SELECT * FROM GGIMG;
ALTER TABLE GGIMG MODIFY(GGSTORENAME VARCHAR2(50));
